name: Invoke the Jenkins pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve Jenkins Crumb
      run: |
       CRUMB=$(curl -u "$JENKINS_USER:$JENKINS_API_TOKEN" -s 'http://172-31-18-171:8080/crumbIssuer/api/json' | jq -r '.crumb')
       echo "CRUMB=$CRUMB" >> $GITHUB_ENV

    - name: Trigger Jenkins Job
      run: |
       curl -X POST "http://172-31-18-171:8080/job/hello-world-web/build?token=mysecret" \
           -u "$JENKINS_USER:$JENKINS_API_TOKEN" \
           -H "Jenkins-Crumb:$CRUMB"
    env:
      JENKINS_USER: ${{ secrets.JENKINS_USER }}
      JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
